# Set a message to a list with 1 item 'none' to disable this message.
# empty-example:
# - none
# You can also add json messages. Generate messages here: http://minecraft.tools/en/json_text.php?
# json-example:
# - @json["", {"text":"json"}]
ranks:
  default: '&8[Player]'
  novice: '&a[Novice]'
  apprentice: '&9[Apprentice]'
  architect: '&b[Architect]'
  designer: '&d[Designer]'
  artisan: '&5[Artisan]'
  master: '&6[Master]'
  
score-syntax:
  structure: 1
  terrain: 2
  organics: 3
  composition: 4
messages:
  credits:
  - '§8§m-----------------------------------------------------'
  - ' '
  - '§6%plugin_name% Info:'
  - ' '
  - '§3Developers: §b%plugin_developers%'
  - '§3Version: §b%plugin_version%'
  - '§3Description: §b%plugin_description%'
  - ' '
  - '§8§m-----------------------------------------------------'
  help:
  - '§8§m-----------------------------------------------------'
  - ' '
  - '§6PlotReview Help:'
  - "§3/submit (confirm/cancel): &bSubmit the plot you're standing on"
  - '§3/review info <id>: §bGet information about a review'
  - '§3/review history: §bOpen a Gui with your past reviews'
  - '§3/review credits: §bDisplay information about this plugin '
  - '§3/review help: §bShow this page'
  - ' '
  - '§8§m-----------------------------------------------------'
  submit:
  - ' '
  - '&8&m-------------------&7[ &6&lPlot Submit &7]§8&m--------------------'
  - ' '
  - '&7[&c!&7] §7You are about to submit a plot for review. The plot can be either accepted or denied. If accepted, your total scores will increase. If not, a staffmember will leave a comment for you.'
  - ' '
  - '&6&lRULES:'
  - '&c[1] &7No copied builds.'
  - '&c[2] &7No pixel art, parkour, or redstone based builds.'
  - '&c[3] &7The build must be completed.'
  - '&c[4] &7You must have made at least 80% of the build.'
  - '  '
  - '@json["",{"text":"Are you sure you want to submit your plot? ","color":"yellow"},{"text":"[","color":"dark_gray"},{"text":"YES","color":"green","clickEvent":{"action":"run_command","value":"/submit confirm"}},{"text":"] [","color":"dark_gray"},{"text":"NO","color":"red","clickEvent":{"action":"run_command","value":"/submit cancel"}},{"text":"]","color":"dark_gray"}]'
  - ' '
  - '&8&m-----------------------------------------------------'
  not_plotowner:
  - "§7[§eREVIEW&7] §cWarning&7: You aren't the owner of this plot!"
  not_on_plot:
  - '§7[§eREVIEW&7] §cWarning&7: You must be on a plot.'
  already_submitted:
  - '§7[§eREVIEW&7] §cWarning&7: This plot has already been submitted!'
  plot_submitted:
  - '§7[§eREVIEW&7] §aCongrats&7! Your plot has been succesfully submitted!'
  no_perms:
  - '§7[§eREVIEW&7] §cWarning&7: Insufficient permissions!'
  cancelled:
  - '§7[§eREVIEW&7] §cWarning&7: Submit has been cancelled!'
  config_reloaded:
  - '§7[§eREVIEW&7] §7Config has been reloaded'
  staff_reviewed_plot:
  - '§7[§eREVIEW&7] §7Your review has been sent!'
  plot_reviewed:
  - '§7[§eREVIEW&7] §7%staff_name% has reviewed your plot!'
  - '§7[§eREVIEW&7] §7Use §b/review summary &7to see the results!'
  confirm_or_cancel:
  - "§7[§eREVIEW&7] &cWarning&7: Please choose 'confirm' or 'cancel' as parameter."
  review_info:
  - '&3ID: &a%ticket_id%'
  - '&3Reviewee: &a%reviewee_name%'
  - '&3Rank: &a%rank%'
  - '&3Date: &a%date%'
  - '&3World: &a%world%'
  - '&3Plot: &a%plot_id%'
  - '&3Stoc-score: &a%stoc%'
  - '&3Average stoc: &a%avg_stoc%'
  - '&3Staff: &a%staff_name%'
  no_past_reviews:
  - "§7[§eREVIEW&7] &cWarning&7: You don't have any reviews!"
  online_reviewed:
  - '§8§m-----------------------------------------------------'
  - ' '
  - '§6Your plot has been reviewed by %staff%!'
  - '§3Ticket ID: §b%review_id%'
  - ' '
  - '§8§m-----------------------------------------------------'
  offline_reviewed:
  - '§8§m-----------------------------------------------------'
  - ' '
  - '§6Your plot has been reviewed by %staff% while you were offline!'
  - '§3Ticket ID: §b%review_id%'
  - '§3Plot: §b%world% %plot%'
  - ' '
  - '§8§m-----------------------------------------------------'
  review_summary:
  - ' '
  - '&8&m-----------------&7[ &6&lReview Summary &7]§8&m------------------'
  - ' '
  - '  &eYour plot scored:'
  - '    &f• &7Structure - %structure_score%'
  - '    &f• &7Terrain - %terrain_score%'
  - '    &f• &7Organics - %organics_score%'
  - '    &f• &7Composition - %composition_score%'
  - ' '
  - ' &7 &ko&r &7>> &6%tot_plot_score% Plot Score &7(%add_tot_plot_score%&7) << &ko'
  - ' &7 &ko&r &7>> &6%rating% Rating &7(%add_rating%&7) << &ko'
  - ' '
  - '&8&m-----------------------------------------------------'
  no_pending_review:
  - "§7[§eREVIEW&7] §cWarning&7: You don't have new reviews!"
  invalid_argument:
  - '§7[§eREVIEW&7] §cWarning&7: Invalid argument!'
  click_to_review:
  - '@json["",{"text":"[","color":"gray"},{"text":"REVIEW","color":"yellow"},{"text":"]","color":"gray"},{"text":" Click ","color":"gray"},{"text":"here","color":"aqua","clickEvent":{"action":"suggest_command","value":"/review score %ticket_id% "},"hoverEvent":{"action":"show_text","value":"§bS-T-O-C"}},{"text":" to review the plot.","color":"gray"}]'
  