name: PlotReview
version: 1.12.2.8.3
description: Review plots
author: Robnoo02
main: me.robnoo02.plotreview.Main

commands:
  review:
    usage: /<command>
    description: Review cmd
  submit:
    usage: /<command>
    description: Submit your plot
  prdebug:
    usage: /<command>
    description: Debug values